import fs from 'node:fs';
import path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { createHash, randomUUID } from 'node:crypto';
import { policy, id, sha } from './github.mjs';
import { hash } from './sdk.mjs';
import { git } from './project.mjs';
import { github, checkedRepository, unchanged, paged } from './submission-github.mjs';

export function forkTarget(snapshot, call = github) {
    const owner = snapshot.actor.id === policy.repositoryOwnerId;
    const name = owner ? policy.repository : `${snapshot.actor.login}/${policy.repository.split('/')[1]}`;
    let repository;
    try { repository = checkedRepository(name, call); }
    catch (error) { if (!owner && error.message === 'GITHUB_NOT_FOUND') return { name, create: true }; throw error; }
    // 所有者在社区仓库内创建投稿分支；其他账号必须使用属于自己的社区 fork。
    if (id(repository.owner.id) !== snapshot.actor.id || (owner
        ? repository.fork || id(repository.id) !== policy.repositoryId
        : !repository.fork || id(repository.parent.id) !== policy.repositoryId)) {
        throw new Error('FORK_IDENTITY_CONFLICT');
    }
    return { name, create: false, id: id(repository.id) };
}

export function writePreview(snapshot, changes, result, fork, title) {
    const files = [...changes].sort(([a], [b]) => a.localeCompare(b)).map(([file, bytes]) => ({
        path: file, size: bytes.length, sha256: hash(bytes), ...(file.endsWith('.json') ? { content: bytes.toString('utf8') } : {}),
    }));
    const identity = hash(Buffer.from(JSON.stringify({ base: snapshot.base, actor: snapshot.actor, files }), 'utf8'));
    return { repository: policy.repository, base: snapshot.base, actor: snapshot.actor, fork, result, files,
        branch: `community/${result.operation.toLowerCase()}/${identity.slice(0, 24)}`, title,
        body: 'Submission data generated by the pinned community wizard. Static checks, source review and protected admission are required.',
        actions: [...(fork.create ? ['CREATE_FORK'] : []), 'CREATE_COMMIT', 'PUSH_BRANCH', 'CREATE_READY_PR'] };
}

function verifyCommit(checkout, head, preview, changes, readGit) {
    const headers = readGit(checkout, 'cat-file', '-p', head).split('\n\n')[0].split('\n');
    if (!isDeepStrictEqual(headers.filter(line => line.startsWith('parent ')), ['parent ' + preview.base])) throw new Error('COMMIT_BASE_CHANGED');
    const changed = readGit(checkout, 'diff', '--no-renames', '--name-status', '-z', preview.base, head).split('\0').filter(Boolean);
    if (changed.length !== preview.files.length * 2) throw new Error('COMMIT_FILES_CHANGED');
    for (let i = 0; i < changed.length; i += 2) {
        if (changed[i] !== 'A' || !changes.has(changed[i + 1])) throw new Error('COMMIT_FILES_CHANGED');
    }
    for (const file of preview.files) {
        const bytes = changes.get(file.path);
        const expected = createHash('sha1').update(Buffer.from(`blob ${bytes.length}\0`)).update(bytes).digest('hex');
        const entry = readGit(checkout, 'ls-tree', '-z', head, '--', file.path);
        if (entry !== `100644 blob ${expected}\t${file.path}\0`) throw new Error('COMMIT_BYTES_CHANGED');
    }
    if (readGit(checkout, 'show', '-s', '--format=%B', head) !== preview.title) throw new Error('COMMIT_MESSAGE_CHANGED');
}

// 确认对象是完整预览；所有外部写入都在两次原生复核之后，普通 push 不覆盖远端分支。
export async function submitPreview({ sdk, snapshot, changes, result, title, confirm, recheck,
    call = github, readGit = git, wait = ms => new Promise(resolve => setTimeout(resolve, ms)) }) {
    unchanged(snapshot, call);
    const fork = forkTarget(snapshot, call);
    const preview = writePreview(snapshot, changes, result, fork, title);
    if (!await confirm(preview)) return { cancelled: true };
    await recheck();
    unchanged(snapshot, call);
    if (!isDeepStrictEqual(forkTarget(snapshot, call), fork)) throw new Error('FORK_CHANGED');
    for (const file of preview.files) {
        const bytes = changes.get(file.path);
        if (!bytes || bytes.length !== file.size || hash(bytes) !== file.sha256) throw new Error('PREVIEW_CHANGED');
    }
    if (changes.size !== preview.files.length) throw new Error('PREVIEW_CHANGED');
    if (fork.create) {
        call(`repos/${policy.repository}/forks`, { method: 'POST', body: { default_branch_only: true } });
        let ready = false;
        for (let attempt = 0; attempt < 30; attempt++) {
            const current = forkTarget(snapshot, call);
            if (!current.create) { ready = true; break; }
            await wait(1000);
        }
        if (!ready) throw new Error('FORK_NOT_READY');
    }
    const repository = checkedRepository(fork.name, call);
    const existing = paged(`repos/${policy.repository}/pulls?state=all&head=${encodeURIComponent(snapshot.actor.login + ':' + preview.branch)}`, call);
    if (existing.length) {
        if (existing.length !== 1 || existing[0].state !== 'open' || existing[0].draft
            || id(existing[0].user.id) !== snapshot.actor.id || id(existing[0].head.repo.id) !== id(repository.id)
            || existing[0].base.sha !== snapshot.base || existing[0].title !== preview.title
            || existing[0].body !== preview.body) throw new Error('EXISTING_PR_CONFLICT');
        // 同一分支的现有 PR 必须仍是预览的全部新增文件。
        const actual = paged(`repos/${policy.repository}/pulls/${existing[0].number}/files`, call);
        if (actual.length !== preview.files.length || actual.some(file => file.status !== 'added'
            || !preview.files.some(expected => expected.path === file.filename))) throw new Error('EXISTING_PR_CONFLICT');
        const { repositoryTree, readBlob } = await import('./submission-github.mjs');
        const tree = repositoryTree(fork.name, sha(existing[0].head.sha), call);
        for (const file of preview.files) if (hash(readBlob(fork.name, tree.get(file.path), call)) !== file.sha256) throw new Error('EXISTING_PR_CONFLICT');
        return { url: existing[0].html_url, reused: true };
    }
    const checkout = fs.mkdtempSync(path.join(sdk.workspace, 'pr-'));
    readGit(checkout, 'init');
    readGit(checkout, 'remote', 'add', 'upstream', `https://github.com/${policy.repository}.git`);
    readGit(checkout, 'remote', 'add', 'origin', `https://github.com/${fork.name}.git`);
    readGit(checkout, 'fetch', '--depth=1', 'upstream', snapshot.base);
    if (readGit(checkout, 'rev-parse', 'FETCH_HEAD') !== snapshot.base) throw new Error('FETCHED_BASE_CHANGED');
    let head;
    try { head = sha(call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha); }
    catch (error) { if (error.message !== 'GITHUB_NOT_FOUND') throw error; }
    const resume = Boolean(head);
    if (resume) {
        readGit(checkout, 'fetch', '--depth=2', 'origin', head);
        if (readGit(checkout, 'rev-parse', 'FETCH_HEAD') !== head) throw new Error('REMOTE_HEAD_CHANGED');
    } else {
        readGit(checkout, 'switch', '--create', preview.branch, snapshot.base);
        for (const [file, bytes] of changes) {
            const destination = sdk.invoke({ command: 'path', root: checkout, path: file, mustExist: false }).path;
            fs.mkdirSync(path.dirname(destination), { recursive: true });
            fs.writeFileSync(destination, bytes, { flag: 'wx' });
        }
        readGit(checkout, '-c', 'core.autocrlf=false', 'add', '--', ...preview.files.map(file => file.path));
        const message = path.join(sdk.workspace, randomUUID() + '-commit.txt');
        fs.writeFileSync(message, title + '\n', 'utf8');
        readGit(checkout, 'commit', '-F', message);
        head = sha(readGit(checkout, 'rev-parse', 'HEAD'));
    }
    verifyCommit(checkout, head, preview, changes, readGit);
    // 交互期间或创建 fork 后再次变化也拒绝提交远端候选。
    unchanged(snapshot, call);
    if (!resume) readGit(checkout, 'push', 'origin', `HEAD:refs/heads/${preview.branch}`);
    if (sha(call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha) !== head) throw new Error('REMOTE_HEAD_CHANGED');
    unchanged(snapshot, call);
    const pull = call(`repos/${policy.repository}/pulls`, { method: 'POST', body: {
        title, head: `${snapshot.actor.login}:${preview.branch}`, base: policy.defaultBranch, draft: false,
        body: preview.body,
    } });
    const actual = call(`repos/${policy.repository}/pulls/${id(pull.number)}`);
    if (actual.draft || actual.state !== 'open' || actual.head.sha !== head || actual.base.sha !== snapshot.base
        || id(actual.user.id) !== snapshot.actor.id || id(actual.head.repo.id) !== id(repository.id)) throw new Error('CREATED_PR_MISMATCH');
    return { url: actual.html_url, head };
}
