import fs from 'node:fs';
import path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { createHash, randomUUID } from 'node:crypto';
import { policy, id, sha } from './github.mjs';
import { hash } from './sdk.mjs';
import { git } from './project.mjs';
import { github, checkedRepository, unchanged, paged, repositoryTree, readBlob } from './submission-github.mjs';
import { checkEmergency } from './emergency-request.mjs';
import { retryStep } from './submission-retry.mjs';

function verifyPreparedFiles(snapshot, pull, files, changes, call, sdk) {
    if (files.some(file => file.status !== 'added')) throw new Error('EXISTING_PR_CONFLICT');
    if (files.length !== changes.size || files.some(file => !changes.has(file.filename))) {
        if (snapshot.branch !== policy.emergencyBranch || !sdk) throw new Error('EXISTING_PR_CONFLICT');
        checkEmergency(pull.number, pull.head.sha, sdk, snapshot.masterBase, call);
    }
    const name = pull.head.repo.full_name;
    const tree = repositoryTree(name, sha(pull.head.sha), call);
    for (const [file, bytes] of changes) if (!readBlob(name, tree.get(file), call).equals(bytes)) throw new Error('EXISTING_PR_CONFLICT');
}

// 恢复到新主线前回读已创建的请求，避免按新 base 计算分支后重复投稿。
export function pendingPrepared(snapshot, changes, call = github, sdk) {
    const requests = [...changes.keys()].filter(file => /^(?:submissions|key-rotations|version-status-requests|ownership-transfers|requests)\//u.test(file));
    const matches = [];
    for (const pull of paged(`repos/${policy.repository}/pulls?state=open`, call)) {
        const files = paged(`repos/${policy.repository}/pulls/${id(pull.number)}/files`, call);
        if (!files.some(file => requests.includes(file.filename))) continue;
        const target = forkTarget(snapshot, call);
        if (target.create || pull.state !== 'open' || id(pull.user.id) !== snapshot.actor.id
            || id(pull.base.repo.id) !== snapshot.repositoryId || pull.base.ref !== (snapshot.branch ?? policy.defaultBranch)
            || id(pull.head?.repo?.id) !== target.id || pull.head.repo.full_name !== target.name) {
            throw new Error('EXISTING_PR_CONFLICT');
        }
        verifyPreparedFiles(snapshot, pull, files, changes, call, sdk);
        matches.push({ url: pull.html_url, head: pull.head.sha, reused: true, draft: Boolean(pull.draft) });
    }
    if (matches.length > 1) throw new Error('EXISTING_PR_CONFLICT');
    return matches[0] ?? null;
}

export function forkTarget(snapshot, call = github) {
    const owner = snapshot.actor.id === policy.repositoryOwnerId;
    const name = owner ? policy.repository : `${snapshot.actor.login}/${policy.repository.split('/')[1]}`;
    let repository;
    try { repository = checkedRepository(name, call); }
    catch (error) { if (!owner && error.message === 'GITHUB_NOT_FOUND') return { name, create: true }; throw error; }
    // 所有者在社区仓库内创建投稿分支；其他账号必须使用属于自己的社区 fork。
    if (id(repository.owner.id) !== snapshot.actor.id || (owner
        ? repository.fork || id(repository.id) !== policy.repositoryId
        : !repository.fork || id(repository.parent.id) !== policy.repositoryId)) {
        throw new Error('FORK_IDENTITY_CONFLICT');
    }
    return { name, create: false, id: id(repository.id) };
}

export function writePreview(snapshot, changes, result, fork, title) {
    const files = [...changes].sort(([a], [b]) => a.localeCompare(b)).map(([file, bytes]) => ({
        path: file, size: bytes.length, sha256: hash(bytes), ...(file.endsWith('.json') ? { content: bytes.toString('utf8') } : {}),
    }));
    const identity = hash(Buffer.from(JSON.stringify({ base: snapshot.base, actor: snapshot.actor, files }), 'utf8'));
    return { repository: policy.repository, base: snapshot.base, ...(snapshot.branch ? { targetBranch: snapshot.branch } : {}), actor: snapshot.actor, fork, result, files,
        branch: `community/${result.operation.toLowerCase()}/${identity.slice(0, 24)}`, title,
        body: snapshot.branch === policy.emergencyBranch
            ? 'Emergency declaration generated by the pinned community wizard. Protected automation verifies GitHub authority and registered keys. Existing publications remain unchanged.'
            : 'Submission data generated by the pinned community wizard. Static checks, source review and protected admission are required.',
        actions: [...(fork.create ? ['CREATE_FORK'] : []), 'CREATE_COMMIT', 'PUSH_BRANCH', 'CREATE_READY_PR'] };
}

export function submissionBranch(snapshot, initial, call = github) {
    let branch = initial;
    for (let attempt = 0; attempt < 32; attempt++) {
        const requests = paged(`repos/${policy.repository}/pulls?state=all&head=${encodeURIComponent(snapshot.actor.login + ':' + branch)}`, call);
        if (!requests.length || requests.some(pr => pr.state === 'open')) return branch;
        if (requests.some(pr => pr.merged_at || pr.state !== 'closed' || id(pr.user.id) !== snapshot.actor.id)) throw new Error('EXISTING_PR_CONFLICT');
        // 已关闭请求保留原分支身份；重投使用新分支，避免沿用同 head 的旧准入检查。
        branch = initial + '-after-' + Math.max(...requests.map(pr => Number(id(pr.number))));
    }
    throw new Error('SUBMISSION_HISTORY_LIMIT');
}

function verifyCommit(checkout, head, preview, changes, readGit) {
    const headers = readGit(checkout, 'cat-file', '-p', head).split('\n\n')[0].split('\n');
    if (!isDeepStrictEqual(headers.filter(line => line.startsWith('parent ')), ['parent ' + preview.base])) throw new Error('COMMIT_BASE_CHANGED');
    const changed = readGit(checkout, 'diff', '--no-renames', '--name-status', '-z', preview.base, head).split('\0').filter(Boolean);
    if (changed.length !== preview.files.length * 2) throw new Error('COMMIT_FILES_CHANGED');
    for (let i = 0; i < changed.length; i += 2) {
        if (changed[i] !== 'A' || !changes.has(changed[i + 1])) throw new Error('COMMIT_FILES_CHANGED');
    }
    for (const file of preview.files) {
        const bytes = changes.get(file.path);
        const expected = createHash('sha1').update(Buffer.from(`blob ${bytes.length}\0`)).update(bytes).digest('hex');
        const entry = readGit(checkout, 'ls-tree', '-z', head, '--', file.path);
        if (entry !== `100644 blob ${expected}\t${file.path}\0`) throw new Error('COMMIT_BYTES_CHANGED');
    }
    if (readGit(checkout, 'show', '-s', '--format=%B', head) !== preview.title) throw new Error('COMMIT_MESSAGE_CHANGED');
}

// 确认对象是完整预览；所有外部写入都在两次原生复核之后，普通 push 不覆盖远端分支。
export async function submitPreview(options) {
    return submitOnce(options);
}

async function submitOnce({ sdk, snapshot, commitBase = snapshot.base, changes, result, title, confirm, recheck,
    actions = [], beforeWrite, write = work => work(), retry,
    call = github, readGit = git, wait = ms => new Promise(resolve => setTimeout(resolve, ms)) }) {
    // 每个写入步骤自行回读结果后才可重试；已完成的步骤不重放。
    const step = (key, work) => retryStep(key, () => { unchanged(snapshot, call); return work(); }, { retry, wait });
    unchanged(snapshot, call);
    if (commitBase !== snapshot.base) {
        const comparison = call(`repos/${policy.repository}/compare/${sha(commitBase)}...${snapshot.base}`);
        if (comparison.status !== 'ahead' || comparison.merge_base_commit?.sha !== commitBase) throw new Error('SUBMISSION_BASE_DIVERGED');
    }
    const fork = forkTarget(snapshot, call);
    // 请求字节与原始父提交共同定位已推送分支；主线推进不能制造第二个投稿。
    const preview = writePreview({ ...snapshot, base: commitBase }, changes, result, fork, title);
    if (commitBase !== snapshot.base) preview.validatedBase = snapshot.base;
    preview.branch = submissionBranch(snapshot, preview.branch, call);
    preview.actions.unshift(...actions);
    if (!await confirm(preview)) return { cancelled: true };
    await step('rechecking', recheck);
    return write(async () => {
    unchanged(snapshot, call);
    if (!isDeepStrictEqual(forkTarget(snapshot, call), fork)) throw new Error('FORK_CHANGED');
    for (const file of preview.files) {
        const bytes = changes.get(file.path);
        if (!bytes || bytes.length !== file.size || hash(bytes) !== file.sha256) throw new Error('PREVIEW_CHANGED');
    }
    if (changes.size !== preview.files.length) throw new Error('PREVIEW_CHANGED');
    if (beforeWrite) await step('publishingCandidate', beforeWrite);
    unchanged(snapshot, call);
    if (!isDeepStrictEqual(forkTarget(snapshot, call), fork)) throw new Error('FORK_CHANGED');
    if (fork.create) {
        await step('creatingFork', async () => {
        if (!forkTarget(snapshot, call).create) return;
        let uncertain;
        try { call(`repos/${policy.repository}/forks`, { method: 'POST', body: { default_branch_only: true } }); }
        catch (error) { if (!error.github) throw error; uncertain = error; }
        let ready = false;
        for (let attempt = 0; attempt < 30; attempt++) {
            const current = forkTarget(snapshot, call);
            if (!current.create) { ready = true; break; }
            await wait(1000);
        }
        if (!ready) throw uncertain ?? new Error('FORK_NOT_READY');
        });
    }
    const repository = checkedRepository(fork.name, call);
    const existing = paged(`repos/${policy.repository}/pulls?state=all&head=${encodeURIComponent(snapshot.actor.login + ':' + preview.branch)}`, call);
    if (existing.length) {
        if (existing.length !== 1 || existing[0].state !== 'open' || existing[0].draft
            || id(existing[0].user.id) !== snapshot.actor.id || id(existing[0].head.repo.id) !== id(repository.id)
            || existing[0].base.ref !== (snapshot.branch ?? policy.defaultBranch) || existing[0].title !== preview.title
            || existing[0].body !== preview.body) throw new Error('EXISTING_PR_CONFLICT');
        // 同一分支的现有 PR 必须仍是预览的全部新增文件。
        const actual = paged(`repos/${policy.repository}/pulls/${existing[0].number}/files`, call);
        verifyPreparedFiles(snapshot, existing[0], actual, changes, call, sdk);
        return { url: existing[0].html_url, head: sha(existing[0].head.sha), reused: true };
    }
    const checkout = fs.mkdtempSync(path.join(sdk.workspace, 'pr-'));
    readGit(checkout, 'init');
    readGit(checkout, 'remote', 'add', 'upstream', `https://github.com/${policy.repository}.git`);
    readGit(checkout, 'remote', 'add', 'origin', `https://github.com/${fork.name}.git`);
    await step('git_fetch', () => readGit(checkout, 'fetch', '--depth=1', 'upstream', commitBase));
    if (readGit(checkout, 'rev-parse', 'FETCH_HEAD') !== commitBase) throw new Error('FETCHED_BASE_CHANGED');
    let head;
    try { head = sha(call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha); }
    catch (error) { if (error.message !== 'GITHUB_NOT_FOUND') throw error; }
    const resume = Boolean(head);
    if (resume) {
        await step('git_fetch', () => readGit(checkout, 'fetch', '--depth=2', 'origin', head));
        if (readGit(checkout, 'rev-parse', 'FETCH_HEAD') !== head) throw new Error('REMOTE_HEAD_CHANGED');
    } else {
        readGit(checkout, 'switch', '--create', preview.branch, commitBase);
        for (const [file, bytes] of changes) {
            const destination = sdk.invoke({ command: 'path', root: checkout, path: file, mustExist: false }).path;
            fs.mkdirSync(path.dirname(destination), { recursive: true });
            fs.writeFileSync(destination, bytes, { flag: 'wx' });
        }
        readGit(checkout, '-c', 'core.autocrlf=false', 'add', '--', ...preview.files.map(file => file.path));
        const message = path.join(sdk.workspace, randomUUID() + '-commit.txt');
        fs.writeFileSync(message, title + '\n', 'utf8');
        readGit(checkout, 'commit', '-F', message);
        head = sha(readGit(checkout, 'rev-parse', 'HEAD'));
    }
    verifyCommit(checkout, head, preview, changes, readGit);
    // 交互期间或创建 fork 后再次变化也拒绝提交远端候选。
    unchanged(snapshot, call);
    if (!resume) {
        await step('git_push', () => {
        let previous;
        try { previous = call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha; }
        catch (error) { if (error.message !== 'GITHUB_NOT_FOUND') throw error; }
        if (previous) {
            if (previous !== head) throw new Error('REMOTE_HEAD_CHANGED');
            return;
        }
        try { readGit(checkout, 'push', 'origin', `HEAD:refs/heads/${preview.branch}`); }
        catch (error) {
            // push 响应丢失不能证明失败；只承认远端仍是本次已验证的精确 head。
            if (!error.github) throw error;
            let remote;
            try { remote = call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha; }
            catch (lookup) { if (lookup.message !== 'GITHUB_NOT_FOUND') throw lookup; }
            if (!remote) throw error;
            if (remote !== head) throw new Error('REMOTE_HEAD_CHANGED');
        }
        });
    }
    if (sha(call(`repos/${fork.name}/git/ref/heads/${preview.branch}`).object.sha) !== head) throw new Error('REMOTE_HEAD_CHANGED');
    unchanged(snapshot, call);
    const pull = await step('creatingPull', () => {
    const prior = paged(`repos/${policy.repository}/pulls?state=all&head=${encodeURIComponent(snapshot.actor.login + ':' + preview.branch)}`, call);
    if (prior.length > 1) throw new Error('EXISTING_PR_CONFLICT');
    if (prior.length) return prior[0];
    let pull;
    try { pull = call(`repos/${policy.repository}/pulls`, { method: 'POST', body: {
        title, head: `${snapshot.actor.login}:${preview.branch}`, base: snapshot.branch ?? policy.defaultBranch, draft: false, maintainer_can_modify: true,
        body: preview.body,
    } }); }
    catch (error) {
        if (!error.github) throw error;
        const found = paged(`repos/${policy.repository}/pulls?state=all&head=${encodeURIComponent(snapshot.actor.login + ':' + preview.branch)}`, call);
        if (!found.length) throw error;
        if (found.length !== 1) throw new Error('EXISTING_PR_CONFLICT');
        pull = found[0];
    }
    return pull;
    });
    const actual = call(`repos/${policy.repository}/pulls/${id(pull.number)}`);
    if (actual.draft || actual.state !== 'open' || actual.head.sha !== head
        || actual.base.ref !== (snapshot.branch ?? policy.defaultBranch)
        || actual.title !== preview.title || actual.body !== preview.body
        || id(actual.user.id) !== snapshot.actor.id || id(actual.head.repo.id) !== id(repository.id)) throw new Error('CREATED_PR_MISMATCH');
    return { url: actual.html_url, head };
    });
}
